export interface NavItem {
	title: string;
	href: string;
	items?: { title: string; href: string }[];
}

export const navigation: NavItem[] = [
	{
		title: 'Getting Started',
		href: '/docs/getting-started',
		items: [
			{ title: 'Installation', href: '/docs/getting-started' },
			{ title: 'Guides', href: '/docs/guides/theming' },
			{ title: '— Theming', href: '/docs/guides/theming' },
			{ title: '— Mobile apps', href: '/docs/guides/mobile' },
			{ title: '— CLI workflow', href: '/docs/guides/cli' },
			{ title: 'Examples', href: '/examples' },
			{ title: 'Playground', href: '/playground' }
		]
	},
	{
		title: 'Components',
		href: '/docs/components',
		items: [
			{ title: 'Overview', href: '/docs/components' },
			{ title: 'Accordion', href: '/docs/components/accordion' },
			{ title: 'Action Sheet', href: '/docs/components/actionsheet' },
			{ title: 'Alert', href: '/docs/components/alert' },
			{ title: 'Avatar Stack', href: '/docs/components/avatarstack' },
			{ title: 'Badge', href: '/docs/components/badge' },
			{ title: 'Bento Grid', href: '/docs/components/bento-grid' },
			{ title: 'Box', href: '/docs/components/box' },
			{ title: 'Button', href: '/docs/components/button' },
			{ title: 'Camera', href: '/docs/components/camera' },
			{ title: 'Card', href: '/docs/components/card' },
			{ title: 'Carousel', href: '/docs/components/carousel' },
			{ title: 'Clipboard', href: '/docs/components/clipboard' },
			{ title: 'Comment', href: '/docs/components/comment' },
			{ title: 'CTA Section', href: '/docs/components/cta-section' },
			{ title: 'Dialog', href: '/docs/components/dialog' },
			{ title: 'Dropdown Menu', href: '/docs/components/dropdown-menu' },
			{ title: 'Editable Label', href: '/docs/components/editable-label' },
			{ title: 'FAB Menu', href: '/docs/components/fabmenu' },
			{ title: 'Feature Grid', href: '/docs/components/feature-grid' },
			{ title: 'Flex', href: '/docs/components/flex' },
			{ title: 'Footer', href: '/docs/components/footer' },
			{ title: 'Gallery', href: '/docs/components/gallery' },
			{ title: 'Grid', href: '/docs/components/grid' },
			{ title: 'Gyroscope', href: '/docs/components/gyroscope' },
			{ title: 'Heatmap', href: '/docs/components/heatmap' },
			{ title: 'Hero', href: '/docs/components/hero' },
			{ title: 'Input', href: '/docs/components/input' },
			{ title: 'List View', href: '/docs/components/listview' },
			{ title: 'Live Badge', href: '/docs/components/live-badge' },
			{ title: 'Mobile Toast', href: '/docs/components/mobile-toast' },
			{ title: 'Navbar', href: '/docs/components/navbar' },
			{ title: 'Notification', href: '/docs/components/notification' },
			{ title: 'Pricing Card', href: '/docs/components/pricing-card' },
			{ title: 'Progress Steps', href: '/docs/components/progress-steps' },
			{ title: 'Pull to Refresh', href: '/docs/components/pulltorefresh' },
			{ title: 'Reaction Bar', href: '/docs/components/reaction-bar' },
			{ title: 'Segmented Control', href: '/docs/components/segmentedcontrol' },
			{ title: 'Select', href: '/docs/components/select' },
			{ title: 'Slide Menu', href: '/docs/components/slidemenu' },
			{ title: 'Stack', href: '/docs/components/stack' },
			{ title: 'Stats', href: '/docs/components/stats' },
			{ title: 'Status Indicator', href: '/docs/components/status-indicator' },
			{ title: 'Swipeable Item', href: '/docs/components/swipeableitem' },
			{ title: 'Tab Bar', href: '/docs/components/tabbar' },
			{ title: 'Tabs', href: '/docs/components/tabs' },
			{ title: 'Table', href: '/docs/components/table' },
			{ title: 'Testimonial', href: '/docs/components/testimonial' },
			{ title: 'Toast', href: '/docs/components/toast' },
			{ title: 'User Profile Card', href: '/docs/components/user-profile-card' },
			{ title: 'Barcode', href: '/docs/components/barcode' },
			{ title: 'Calendar', href: '/docs/components/calendar' },
			{ title: 'Charts', href: '/docs/components/charts' },
			{ title: 'Infinite Scroll', href: '/docs/components/infinite-scroll' },
			{ title: 'Kanban', href: '/docs/components/kanban' },
			{ title: 'Mention', href: '/docs/components/mention' },
			{ title: 'QR Code', href: '/docs/components/qr-code' },
			{ title: 'Split View', href: '/docs/components/split-view' },
			{ title: 'Validate', href: '/docs/components/validate' },
			{ title: 'Virtual List', href: '/docs/components/virtual-list' },
			{ title: 'MD3 Badge', href: '/docs/components/md3-badge' },
			{ title: 'MD3 Bottom Sheet', href: '/docs/components/md3-bottom-sheet' },
			{ title: 'MD3 Chip', href: '/docs/components/md3-chip' },
			{ title: 'MD3 FAB', href: '/docs/components/md3-fab' },
			{ title: 'MD3 Navigation Bar', href: '/docs/components/md3-navigation-bar' },
			{ title: 'MD3 Navigation Rail', href: '/docs/components/md3-navigation-rail' },
			{ title: 'MD3 Progress Indicator', href: '/docs/components/md3-progress-indicator' },
			{ title: 'MD3 Radio', href: '/docs/components/md3-radio' },
			{ title: 'MD3 Ripple', href: '/docs/components/md3-ripple' },
			{ title: 'MD3 Search Bar', href: '/docs/components/md3-search-bar' },
			{ title: 'MD3 Segmented Button', href: '/docs/components/md3-segmented-button' },
			{ title: 'MD3 Snackbar', href: '/docs/components/md3-snackbar' },
			{ title: 'MD3 Text Field', href: '/docs/components/md3-text-field' },
			{ title: 'MD3 Switch', href: '/docs/components/md3-switch' },

			{ title: 'MD3 Top App Bar', href: '/docs/components/md3-top-app-bar' },
			{ title: 'Flat Arrow Card', href: '/docs/components/flat-arrow-card' },
			{ title: 'Flat Blob Card', href: '/docs/components/flat-blob-card' },
			{ title: 'Flat Circle Avatar', href: '/docs/components/flat-circle-avatar' },
			{ title: 'Flat Circle Grid', href: '/docs/components/flat-circle-grid' },
			{ title: 'Flat Cross Badge', href: '/docs/components/flat-cross-badge' },
			{ title: 'Flat Diamond Badge', href: '/docs/components/flat-diamond-badge' },
			{ title: 'Flat Ellipse Badge', href: '/docs/components/flat-ellipse-badge' },
			{ title: 'Flat Hexagon Grid', href: '/docs/components/flat-hexagon-grid' },
			{ title: 'Flat Octagon Card', href: '/docs/components/flat-octagon-card' },
			{ title: 'Flat Parallelogram Card', href: '/docs/components/flat-parallelogram-card' },
			{ title: 'Flat Pentagon Stat', href: '/docs/components/flat-pentagon-stat' },
			{ title: 'Flat Star Card', href: '/docs/components/flat-star-card' },
			{ title: 'Flat Trapezoid Card', href: '/docs/components/flat-trapezoid-card' },
			{ title: 'Flat Triangle Alert', href: '/docs/components/flat-triangle-alert' },
			{ title: 'Flat Wave Section', href: '/docs/components/flat-wave-section' },
			{ title: 'Flat Zigzag Divider', href: '/docs/components/flat-zigzag-divider' }
		]
	},
	{
		title: 'Design Tokens',
		href: '/docs/tokens',
		items: [{ title: 'Tokens', href: '/docs/tokens' }]
	},
	{
		title: 'Themes',
		href: '/docs/themes',
		items: [
			{ title: 'Overview', href: '/docs/themes' },
			{ title: 'shadcn', href: '/docs/themes' },
			{ title: 'Material Design 3', href: '/docs/themes/md3' },
			{ title: 'Flat', href: '/docs/themes/flat' },
			{ title: 'Glass', href: '/docs/themes/glass' },
			{ title: 'Brutalist', href: '/docs/themes/brutalist' },
			{ title: 'Neumorphism', href: '/docs/themes/neumorphism' },
			{ title: 'Retro', href: '/docs/themes/retro' },
			{ title: 'Cyberpunk', href: '/docs/themes/cyberpunk' },
			{ title: 'Minimalist', href: '/docs/themes/minimalist' }
		]
	}
];
